//
// Created by plaggm on 4/18/19.
//

#ifndef NEMO2_NEMO_BUILD_OPTIONS_H
#define NEMO2_NEMO_BUILD_OPTIONS_H
#pragma once
#define DEF_TN_NEURONS_PER_CORE 256
#define DEF_TN_WEIGHTS_PER_NEURON 4
#define DEF_TN_MAX_NEURON_OUTPUTS 1
#define DEF_THREADED_WRITER 1
#define DEF_LIF_NEURONS_PER_CORE 256
#define DEF_LIF_NUM_OUTPUTS 256


#endif //NEMO2_NEMO_BUILD_OPTIONS_H
